# Dependencies
markdown:         kramdown
highlighter:      rouge
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bongjava
tagline:          '봉자바 블로그'
description:      '봉자바의 블로그입니다.'
url:              http://bongjava.com

author:
  name:           '봉자바'
  url:            https://www.facebook.com/bongjava

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/bongjava

facebook:
  url:            https://www.facebook.com/bongjava

blog:
  url:            http://baby.bongjava.com

instagram:
  url:            https://www.instagram.com/bongjava